import type { PlanResponse } from "@/types";

// A known-good demo plan so the grid + timeline hero works without a backend.
// Shows the lettuce -> beans succession handoff in the same cells.
export const SAMPLE_PLAN: PlanResponse = {
  plan: {
    id: "sample",
    garden_id: "sample",
    status: "complete",
    estimated_minimum_yield_kg: 31,
    estimated_maximum_yield_kg: 52,
    estimated_minimum_savings: 210,
    estimated_maximum_savings: 320,
    space_utilization: 0.86,
  },
  assignments: [
    {
      id: "a1",
      crop_id: "lettuce",
      crop: "Lettuce",
      x: 0,
      y: 0,
      width_cells: 2,
      height_cells: 2,
      plant_date: "2027-04-15",
      harvest_start: "2027-06-01",
      harvest_end: "2027-06-15",
      plant_count: 4,
      estimated_minimum_yield_kg: 1.5,
      estimated_maximum_yield_kg: 2.5,
      successor_assignment_id: "a2",
      explanation:
        "Cool-season crop placed in a partial-sun corner; harvested before beans need the space.",
    },
    {
      id: "a2",
      crop_id: "bush_beans",
      crop: "Bush Beans",
      x: 0,
      y: 0,
      width_cells: 2,
      height_cells: 2,
      plant_date: "2027-06-16",
      harvest_start: "2027-08-01",
      harvest_end: "2027-09-10",
      plant_count: 6,
      estimated_minimum_yield_kg: 2,
      estimated_maximum_yield_kg: 3.5,
      successor_assignment_id: null,
      explanation: "Succeeds lettuce in the same cells once it is cleared in mid-June.",
    },
    {
      id: "a3",
      crop_id: "tomato",
      crop: "Tomato",
      x: 2,
      y: 0,
      width_cells: 2,
      height_cells: 3,
      plant_date: "2027-05-10",
      harvest_start: "2027-07-20",
      harvest_end: "2027-09-20",
      plant_count: 2,
      estimated_minimum_yield_kg: 8,
      estimated_maximum_yield_kg: 14,
      successor_assignment_id: null,
      explanation: "Tall crop placed on the north edge to avoid shading shorter crops.",
    },
    {
      id: "a4",
      crop_id: "carrot",
      crop: "Carrot",
      x: 0,
      y: 2,
      width_cells: 2,
      height_cells: 1,
      plant_date: "2027-04-20",
      harvest_start: "2027-07-01",
      harvest_end: "2027-07-20",
      plant_count: 24,
      estimated_minimum_yield_kg: 2,
      estimated_maximum_yield_kg: 3,
      successor_assignment_id: null,
      explanation: "Root crop tucked below the lettuce bed for early-season use.",
    },
  ],
  unplaced: [
    {
      crop_id: "watermelon",
      reason:
        "Needs ~1.8 m² per plant; garden too small. Try a compact cucumber instead.",
    },
  ],
};
